### ISSUE TITLE
About the DCN

### ISSUE THREAD

**Issue by PureMmm** [zhiqiiiiiii/PDWN_for_Video_Interp#1]
Hello, I saw that you said you used DCN_v2(with mask) in the paper, but the code you provided used DCN_V1?So which version did you use for the performance results in your paper?
Thank!

**Comment by zhiqiiiiiii** [comment]
Hi, thanks for your interest in our work. This is an earlier version of our model. I will publish the version used in our paper very soon. Stay tuned!

**Comment by zdyshine** [comment]
Thanks for sharing the code. Is there any plan to release the paper version code?

**Comment by zhiqiiiiiii** [comment]
Hi, the paper version code including the model has been released!
